---
- name: 'Update apt cache...'
  when: ansible_pkg_mgr == 'apt'
  become: '{{ gpg_privilege_escalation }}'
  become_user: root
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: 'Install GPG os pkgs...'
  become: '{{ gpg_privilege_escalation }}'
  become_user: root
  ansible.builtin.package:
    name: '{{ gpg_os_pkgs }}'
    state: present
