---
- name: Converge
  hosts: all
  collections:
    - jcalavia_org.setup
  tasks:
    - name: "Include setup"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
