- name: 'Setup Development machine'
  hosts: all
  roles:
    - { role: jcalavia_org.setup.git }
    - { role: jcalavia_org.setup.nvim }
    - { role: jcalavia_org.setup.tmux }
    - { role: jcalavia_org.setup.opencode }
