---
- name: 'Ensure plugins directory exists'
  ansible.builtin.file:
    path: '{{ tmux_plugins_dir }}'
    state: directory
    mode: '0755'

- name: 'Clone TPM'
  ansible.builtin.git:
    repo: '{{ tmux_tpm_uri }}'
    dest: '{{ tmux_tpm_path }}'
    version: master
    depth: 1

- name: 'Install plugins via TPM'
  ansible.builtin.shell: >
    {{ tmux_tpm_path }}/bin/install_plugins
  args:
    chdir: '{{ tmux_plugins_dir }}'
  environment:
    TMUX_PLUGIN_MANAGER_PATH: '{{ tmux_plugins_dir }}/'
  changed_when: false
  when: tmux_tpm_enable
