---
galaxy_info:
  author: 'Jorge Calavia'
  description: 'Role to install and configure OpenCode with plugins'
  company: 'Calavia Org'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.19'
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - dev
    - opencode
    - ai
dependencies:
  - role: git
    git_skip_configure: true
  - role: mise
