---
galaxy_info:
  author: 'Jorge Calavia'
  description: 'Role to install and configure mise (rtx) with global tool versions'
  company: 'Calavia Org'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.19'
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - dev
    - mise
    - versionmanager
    - python
    - java
    - node
    - go
dependencies: []
