name: Release Collection

on:
  push:
    branches:
      - main
      - release-*

jobs:
  release:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox-ansible, includes tox
        run: python3 -m pip install tox-ansible

      - name: Run sanity test
        run: >-
          python3 -m tox
          --ansible
          -e sanity-py3.12-2.19
          --conf tox-ansible.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit test
        run: >-
          python3 -m tox
          --ansible
          -e unit-py3.12-2.19
          --conf tox-ansible.ini
          --
          --show-capture=all
          --cov=unit
          --cov-report=xml
          --junit-xml=tests/reports/unit.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration test
        run: >-
          python3 -m tox
          --ansible
          -e integration-py3.12-2.19
          --conf tox-ansible.ini
          --
          --show-capture=all
          --junit-xml=tests/reports/integration.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
